name = Larche custom
description = Larche layout demonstrating mobile first and Susy.
preview = preview.png
template = larche-layout

; Regions
regions[branding]       = Branding
regions[navigation]     = Navigation bar
regions[header]         = Header
regions[highlighted]    = Highlighted

regions[sidebar_first]  = First column
regions[sidebar_first]  = Second column

regions[help]           = Help

regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar

regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/larche/larche.layout.css
